echo "start"

python main.py --root_path ~/     --video_path ~/Thesis/FSL105_jpg_30     --annotation_path ~/Thesis/FSL105_anno_30/ucf101_01.json       --result_path Efficient-3DCNNs/flow/result_mobilenet_test       --dataset ucf101        --n_classes 30  --model mobilenet       --width_mult 0.5        --train_crop center     --learning_rate 0.1    --sample_duration 16    --downsample 2  --batch_size 64         --n_threads 16  --checkpoint 1  --n_val_samples 1 --modality flow --test --no_train --no_val --crop_position_in_test c --resume_path /home/matthew/Efficient-3DCNNs/flow/result_mobilenet/ucf101_mobilenet_0.5x_flow_16_best.pth
            
python main.py --root_path ~/     --video_path ~/Thesis/FSL105_jpg_30     --annotation_path ~/Thesis/FSL105_anno_30/ucf101_01.json       --result_path Efficient-3DCNNs/flow/results_shufflenet_test    --dataset ucf101        --n_classes 30  --model shufflenet       --width_mult 0.5        --groups 3 --train_crop center     --learning_rate 0.1    --sample_duration 16    --downsample 2  --batch_size 64         --n_threads 16  --checkpoint 1  --n_val_samples 1 --modality flow --test --no_train --no_val --crop_position_in_test c --resume_path /home/matthew/Efficient-3DCNNs/flow/results_shufflenet/ucf101_shufflenet_0.5x_flow_16_best.pth

python main.py --root_path ~/     --video_path ~/Thesis/FSL105_jpg_30     --annotation_path ~/Thesis/FSL105_anno_30/ucf101_01.json       --result_path Efficient-3DCNNs/rgbflow/result_mobilenet_test       --dataset ucf101        --n_classes 30  --model mobilenet       --width_mult 0.5        --train_crop center     --learning_rate 0.1    --sample_duration 16    --downsample 2  --batch_size 64         --n_threads 16  --checkpoint 1  --n_val_samples 1 --modality rgbflow --test --no_train --no_val --crop_position_in_test c --resume_path /home/matthew/Efficient-3DCNNs/rgbflow/result_mobilenet/ucf101_mobilenet_0.5x_rgbflow_16_best.pth
            
python main.py --root_path ~/     --video_path ~/Thesis/FSL105_jpg_30     --annotation_path ~/Thesis/FSL105_anno_30/ucf101_01.json       --result_path Efficient-3DCNNs/rgbflow/results_shufflenet_test    --dataset ucf101        --n_classes 30  --model shufflenet       --width_mult 0.5        --groups 3 --train_crop center     --learning_rate 0.1    --sample_duration 16    --downsample 2  --batch_size 64         --n_threads 16  --checkpoint 1  --n_val_samples 1 --modality rgbflow --test --no_train --no_val --crop_position_in_test c --resume_path /home/matthew/Efficient-3DCNNs/rgbflow/results_shufflenet/ucf101_shufflenet_0.5x_rgbflow_16_best.pth

echo "Completed 4 models"
